# Generated by Django 5.2.10 on 2026-01-16 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kostenstelle',
                'verbose_name_plural': 'Kostenstellen',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Systemprotokoll', 'verbose_name_plural': 'Systemprotokolle'},
        ),
        migrations.AddField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Austrittsdatum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sage_cloud_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sage Cloud ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sage_local_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sage Local ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.department', verbose_name='Abteilung'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mitarbeiter-ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.costcenter', verbose_name='Kostenstelle'),
        ),
        migrations.CreateModel(
            name='ImportedLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sage_request_id', models.CharField(max_length=100, unique=True, verbose_name='Sage Anfrage-ID')),
                ('leave_type', models.CharField(max_length=100, verbose_name='Urlaubsart')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('days_count', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Anzahl Tage')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('approved_by', models.CharField(blank=True, max_length=200, verbose_name='Genehmigt von')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Rohdaten')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='dms.employee')),
            ],
            options={
                'verbose_name': 'Importierter Urlaubsantrag',
                'verbose_name_plural': 'Importierte Urlaubsanträge',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sage_local_wsdl_url', models.URLField(blank=True, help_text='z.B. http://192.168.x.x:33033/?wsdl', verbose_name='Sage Local WSDL URL')),
                ('sage_local_api_user', models.CharField(blank=True, max_length=100, verbose_name='Sage Local API-Benutzer')),
                ('encrypted_sage_local_api_key', models.BinaryField(blank=True, null=True, verbose_name='Sage Local API-Schlüssel (verschlüsselt)')),
                ('sage_local_timeout', models.PositiveIntegerField(default=30, verbose_name='Sage Local Timeout (Sekunden)')),
                ('sage_cloud_api_url', models.URLField(blank=True, help_text='z.B. https://mycompany.sage.hr/api', verbose_name='Sage Cloud API URL')),
                ('encrypted_sage_cloud_api_key', models.BinaryField(blank=True, null=True, verbose_name='Sage Cloud API-Schlüssel (verschlüsselt)')),
                ('ms_graph_tenant_id', models.CharField(blank=True, max_length=100, verbose_name='MS Graph Tenant ID')),
                ('ms_graph_client_id', models.CharField(blank=True, max_length=100, verbose_name='MS Graph Client ID')),
                ('encrypted_ms_graph_secret', models.BinaryField(blank=True, null=True, verbose_name='MS Graph Secret (verschlüsselt)')),
                ('document_storage_path', models.CharField(default='/data/personalakten', help_text='Basispfad für Personalakten', max_length=500, verbose_name='Dokumentenspeicherpfad')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Systemeinstellung',
                'verbose_name_plural': 'Systemeinstellungen',
            },
        ),
        migrations.CreateModel(
            name='ImportedTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('month', models.PositiveIntegerField(verbose_name='Monat')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Gesamtstunden')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Überstunden')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Rohdaten')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='dms.employee')),
            ],
            options={
                'verbose_name': 'Importierte Zeiterfassung',
                'verbose_name_plural': 'Importierte Zeiterfassungen',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
