# Generated by Django 5.2.10 on 2026-01-17 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_remove_document_storage_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('SAGE', 'Sage Archiv'), ('MANUAL', 'Manuelle Eingabe'), ('EMAIL', 'E-Mail')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Wartend'), ('RUNNING', 'Läuft'), ('COMPLETED', 'Abgeschlossen'), ('FAILED', 'Fehlgeschlagen')], default='PENDING', max_length=20)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('skipped_files', models.PositiveIntegerField(default=0)),
                ('error_files', models.PositiveIntegerField(default=0)),
                ('current_file', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scan-Auftrag',
                'verbose_name_plural': 'Scan-Aufträge',
                'ordering': ['-started_at'],
            },
        ),
    ]
