# Generated by Django 5.2.10 on 2026-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_add_tags_and_matching_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, db_index=True, help_text='Monat/Jahr zu dem das Dokument gehört', null=True, verbose_name='Belegdatum'),
        ),
    ]
