# Generated by Django 5.2.10 on 2026-01-19 14:33

import dms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_add_period_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='encrypted_content',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='encrypted_content',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Dokument-Datei (Azure Blob Storage in Production)', null=True, upload_to=dms.models.document_upload_path, verbose_name='Datei'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=dms.models.version_upload_path, verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
