# Generated by Django 5.2.10 on 2026-01-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_saas_refactoring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfig',
        ),
        migrations.AddField(
            model_name='tenant',
            name='ingest_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token für E-Mail-Routing (upload.<token>@dms.cloud)', max_length=64, null=True, unique=True, verbose_name='Ingest-Token'),
        ),
    ]
