# Generated by Django 5.2.10 on 2026-01-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_central_email_ingest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Position/Jobtitel'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('ONBOARDING', 'Onboarding'), ('OFFBOARDING', 'Offboarding'), ('ARCHIVED', 'Archiviert')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('reminder_type', models.CharField(choices=[('CONTRACT_EXPIRY', 'Vertragsablauf'), ('PROBATION_END', 'Probezeit-Ende'), ('REVIEW_DUE', 'Prüfung fällig'), ('CERTIFICATE_EXPIRY', 'Zertifikat-Ablauf'), ('RETENTION_EXPIRY', 'Aufbewahrungsfrist'), ('CUSTOM', 'Benutzerdefiniert')], default='CUSTOM', max_length=30, verbose_name='Typ')),
                ('due_date', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('remind_days_before', models.PositiveIntegerField(default=14, verbose_name='Tage vorher erinnern')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('COMPLETED', 'Erledigt'), ('DISMISSED', 'Verworfen')], default='PENDING', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='dms.document', verbose_name='Dokument')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='dms.employee', verbose_name='Mitarbeiter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='dms.tenant')),
            ],
            options={
                'verbose_name': 'Wiedervorlage',
                'verbose_name_plural': 'Wiedervorlagen',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
