# Generated by Django 5.2.10 on 2026-01-20 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_token_length_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='E-Mail des ersten Mandanten-Administrators', max_length=254, verbose_name='Kontakt-E-Mail'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kontaktperson'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_status',
            field=models.CharField(choices=[('CREATED', 'Erstellt'), ('INVITED', 'Einladung gesendet'), ('ACTIVE', 'Aktiv'), ('SUSPENDED', 'Gesperrt')], default='CREATED', max_length=20, verbose_name='Onboarding-Status'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einwilligung erteilt am'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP bei Einwilligung'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='consent_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Einwilligungsversion'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('USER', 'Benutzer')], default='USER', max_length=20, verbose_name='Rolle'),
        ),
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('ACCEPTED', 'Angenommen'), ('EXPIRED', 'Abgelaufen'), ('REVOKED', 'Widerrufen')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(verbose_name='Gültig bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL, verbose_name='Angenommen von')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='dms.tenant')),
            ],
            options={
                'verbose_name': 'Mandanten-Einladung',
                'verbose_name_plural': 'Mandanten-Einladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='invited_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.tenantinvite', verbose_name='Eingeladen über'),
        ),
    ]
