# Generated by Django 5.2.10 on 2026-01-22 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_tenant_onboarding_gdpr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='onboarding_status',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, help_text='Optional: Sage-Ordnername für Import (z.B. 0000001)', max_length=20, null=True, unique=True, verbose_name='Sage-Mandanten-Code'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Automatisch generierter eindeutiger Identifier', unique=True, verbose_name='System-ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('license_max_mandanten', models.PositiveIntegerField(default=1, help_text='Maximale Anzahl an Mandanten für diesen Kunden', verbose_name='Max. Mandanten')),
                ('license_max_users', models.PositiveIntegerField(default=5, help_text='Maximale Anzahl an Benutzern für diesen Kunden', verbose_name='Max. Benutzer')),
                ('license_max_personnel_files', models.PositiveIntegerField(default=100, help_text='Maximale Anzahl an Personalakten für diesen Kunden', verbose_name='Max. Personalakten')),
                ('onboarding_status', models.CharField(choices=[('CREATED', 'Erstellt'), ('INVITED', 'Einladung gesendet'), ('ACTIVE', 'Aktiv'), ('SUSPENDED', 'Gesperrt')], default='CREATED', max_length=20, verbose_name='Onboarding-Status')),
                ('contact_email', models.EmailField(blank=True, help_text='E-Mail des Unternehmens-Administrators', max_length=254, verbose_name='Kontakt-E-Mail')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Kontaktperson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='dms.company', verbose_name='Unternehmen'),
        ),
    ]
