# Generated by Django 5.2.10 on 2026-01-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0019_add_company_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='encrypted_sage_cloud_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='encrypted_samba_password',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='sage_cloud_api_url',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='samba_username',
        ),
        migrations.AddField(
            model_name='systemlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, ist dieser Log nur für diesen Mandanten sichtbar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dms.tenant', verbose_name='Mandant'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azure_storage_connection_string_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Azure Storage Connection String (verschlüsselt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azure_storage_container_name',
            field=models.CharField(blank=True, default='documents', max_length=100, verbose_name='Azure Blob Container Name'),
        ),
    ]
