# Generated by Django 5.2.10 on 2026-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0020_cleanup_systemsettings_add_tenant_to_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='encrypted_dek',
            field=models.BinaryField(blank=True, help_text='Tenant-spezifischer Verschlüsselungsschlüssel (KEK-verschlüsselt)', null=True, verbose_name='Verschlüsselter DEK'),
        ),
    ]
