# Generated by Django 5.2.10 on 2026-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0021_add_tenant_encrypted_dek'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agent_ip',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Agent-IP'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent zuletzt gesehen'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_queue_size',
            field=models.IntegerField(default=0, verbose_name='Agent-Warteschlange'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Agent-Status'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Agent-Version'),
        ),
    ]
