# Generated by Django 4.2.27 on 2026-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0022_add_tenant_agent_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='ingest_token',
        ),
        migrations.AddField(
            model_name='tenant',
            name='ingest_token_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash des E-Mail/Upload-Tokens', max_length=64, null=True, unique=True, verbose_name='Ingest-Token (Hash)'),
        ),
    ]
