# Generated by Django 4.2.27 on 2026-01-23 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0023_remove_tenant_ingest_token_tenant_ingest_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='support_access_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_support_access', to=settings.AUTH_USER_MODEL, verbose_name='Support-Zugriff erteilt von'),
        ),
        migrations.AddField(
            model_name='company',
            name='support_access_granted_until',
            field=models.DateTimeField(blank=True, help_text='Bis zu diesem Zeitpunkt darf der Root-Admin auf die Daten zugreifen.', null=True, verbose_name='Support-Zugriff gültig bis'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_admin', models.BooleanField(default=False, help_text='Ist Hauptansprechpartner für dieses Unternehmen', verbose_name='Haupt-Administrator')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='dms.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unternehmens-Administrator',
                'verbose_name_plural': 'Unternehmens-Administratoren',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
